# Generated by Django 3.1.1 on 2020-09-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('did', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=200, null=True)),
                ('dgender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('dage', models.IntegerField()),
                ('daddress', models.CharField(max_length=200, null=True)),
                ('dphone', models.CharField(max_length=200, null=True)),
                ('demail', models.EmailField(max_length=200, null=True)),
            ],
        ),
    ]
