# Generated by Django 3.1.1 on 2020-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200917_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='crequest',
            field=models.IntegerField(default=0),
        ),
    ]
