# Generated by Django 3.1.1 on 2020-09-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200917_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hid',
            new_name='id',
        ),
    ]
