# Generated by Django 3.1.1 on 2020-09-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200917_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='id',
            new_name='hid',
        ),
    ]
