# Generated by Django 3.1.1 on 2020-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200917_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='trequest',
            field=models.IntegerField(default=0),
        ),
    ]
