# Generated by Django 3.1.1 on 2020-09-19 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200919_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingdonation',
            name='expirydate',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
    ]
