# Generated by Django 3.1.1 on 2020-09-19 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_ongoingdonation_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingdonation',
            name='donatedate',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
        migrations.AlterField(
            model_name='ongoingdonation',
            name='expirydate',
            field=models.DateField(default=datetime.date(2020, 9, 26)),
        ),
    ]
