# Generated by Django 3.1.1 on 2020-09-20 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200919_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingdonation',
            name='donatedate',
            field=models.DateField(default=datetime.date(2020, 9, 20)),
        ),
        migrations.AlterField(
            model_name='ongoingdonation',
            name='expirydate',
            field=models.DateField(default=datetime.date(2020, 9, 27)),
        ),
    ]
