# Generated by Django 3.1.1 on 2020-09-23 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200920_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('bid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bloodgroup', models.CharField(max_length=10, null=True)),
                ('quantity', models.IntegerField()),
                ('donatedate', models.DateField(default=datetime.date(2020, 9, 23))),
                ('expirydate', models.DateField(default=datetime.date(2020, 11, 4))),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Process', 'In Process')], default='In Process', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 9, 23)),
        ),
        migrations.AddField(
            model_name='donor',
            name='dweight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dage',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OngoingDonation',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donor'),
        ),
    ]
